main:
    random_seed: '8512'
    saved_dir: '/home/tony/Mango/models/resnet50_unfreeze10/train'

dataset:
    name: 'MangoDataset'
    kwargs:
        data_dir: "/home/tony/datasets/Mango/traindev"
        train_data_csv: "/home/tony/datasets/Mango/train.csv"
        valid_data_csv: "/home/tony/datasets/Mango/dev.csv"
        transforms:
            - name: 'Normalize'
        augments:
        resize: 512


dataloader:
    name: 'Dataloader'
    kwargs:
        train:
            batch_size: 4
        valid:
            batch_size: 2
        shuffle: true
        num_workers: 8

net:
    name: 'ResNet50'
    kwargs:
      num_classes: 3
      pretrained: True
        

losses:
    - name: 'CrossEntropyLossWrapper'
      weight: 1.0

metrics:
    - name: 'Accuracy'

optimizer:
    # name: 'Adam'
    # kwargs:
    #     lr: 0.1
    #     weight_decay: 0
    #     amsgrad: false
    name: 'SGD'
    kwargs:
        lr: 0.01
        momentum: 0.9
        weight_decay: 0.0005

lr_scheduler:
    name: 'MultiStepLR'
    kwargs:
        milestones: [10, 100]
        gamma: 0.1

logger:
    name: 'MangoLogger'
    kwargs:
        dummy_input: [16, 1, 256, 256]

monitor:
    name: 'Monitor'
    kwargs:
        mode: 'max'
        target: 'Accuracy'
        saved_freq: 10
        early_stop: 0

trainer:
    name: 'MangoTrainer'
    kwargs:
        device: 'cuda:0'
        num_epochs: 200
        freeze_param: True
        unfreeze_epoch: 10